[package]
name = "rabbitmq-tutorials"
version = "0.1.0"
edition = "2021"


[dependencies]
futures-lite = "1.12"
lapin = "2.1"
tokio = { version = "1.26", features = ["macros", "rt", "rt-multi-thread"] }
uuid = { version = "1.3", features = ["v4"] }
