[package]
name = "rabbitmq-tutorials"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-lite = "1.13"
lapin = "2.2"
tokio = { version = "1.28", features = ["macros", "rt", "rt-multi-thread"] }
uuid = { version = "1.3", features = ["v4"] }
