[package]
name = "rabbitmq-tutorials"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-lite = "2.5"
lapin = "2.5"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
uuid = { version = "1.11", features = ["v4"] }
